### PR TITLE
Updated for requested changes after false merge

### PR DESCRIPTION
**Pull request by alef-garrido**
Invalid merge after updating files to apply requested changes.
Creating this pull request to submit changes for code review. 

Previous pull request: https://github.com/alef-garrido/PortfolioAlef/pull/5

### CODE REVIEW

**Review by Shaher-11 — COMMENTED** [review]
## _Status:_ Invalid:x:
## Hello @alef-garrido 
This Code Review Request will be marked as invalid in your Dashboard because the linter checks are not passing as required for this project.
Please make the necessary changes and submit another code review request once you are ready! :smiley:

**Review by smcommits — COMMENTED** [review]
Hi @alef-garrido, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

The setup for GitHub actions is missing from your repository. Therefore, the linters checks are not initialized in your pull request. Please make sure to setup GitHub actions before requesting a review. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by alef-garrido** [comment]
Hi @smcommits, the previous reviewer said the linters were not passing. but didn't mention anything about the confing being missing. Any clues on how can i solve this? I'm checking my repo's hidden files and the linter files are there. 
I would appreciate any advise.

**Comment by alef-garrido** [comment]
It's now fixed. There was no config missing, just a merge conflict to be solved. Thank you anyway!

**Review by Dipeshtwis — CHANGES_REQUESTED** [review]
Hi @alef-garrido , 

## I'm mentioning here, so that next reviewer won't confuse. This is the 2nd review and only one review left for this PR.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️

- [ ] Still, the footer has same issue mentioned [here](https://github.com/alef-garrido/PortfolioAlef/pull/5#discussion_r649591315). Below is the screenshot of how it looks, Make sure to use margin and padding in the mobile version to create a gap.

Screenshot 2021-06-12 at 03-30-26 Alef's Portfolio


## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- Same as the previous reviewer mentioned it in [here](https://github.com/alef-garrido/PortfolioAlef/pull/5#discussion_r649585081). It will make your website even better on all screens.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**

-------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alef-garrido** [comment]
Hi @Dipeshtwis, I believe your seeing the live demo, maybe. the last commit i did has both of the changes solved. 
Would you be so kind to verify if your seeing the right version of the code? 
I was checking my code with my coding partner and it's looking fine.   

Screenshot from 2021-06-11 18-15-38
Screenshot from 2021-06-11 18-16-29

**Comment by Davidosky007** [comment]
Hi @alef-garrido, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

[OPTIONAL]
The footer section still looks different as the previous reviewer mentioned. here is a hint to fix this ( add some margin to the `div` wrapping the social icons) 
Screenshot (57)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
